import 'package:ecom_app/models/product.dart';

class MyProducts{
  static List<Product> allProducts = [
    Product(
      id: '1',
      name: 'Nike Air Max 200',
      category: 'Trending',
      image: 'assets/sneakers/1.png',
      description:
      'Clean lines, versatile and timeless, the best quality fabric with sustainable air cushion which provides day long comfort.',
      price: 700,
      quantity: 1,
    ),
    Product(
      id: '2',
      name: 'Adidas Ultraboost 21',
      category: 'Running',
      image: 'assets/sneakers/2.png',
      description:
      'Designed for high performance running, featuring Boost technology for ultimate energy return.',
      price: 180,
      quantity: 1,
    ),
    Product(
      id: '3',
      name: 'New Balance Fresh Foam 1080v11',
      category: 'Running',
      image: 'assets/sneakers/2.png',
      description:
      'Engineered with a Fresh Foam midsole, providing luxurious cushioning for the ultimate ride.',
      price: 150,
      quantity: 1,
    ),
    Product(
      id: '4',
      name: 'Nike React Infinity Run Flyknit',
      category: 'Running',
      image: 'assets/sneakers/1.png',
      description:
      'Innovative design with React foam and Flyknit upper for lightweight comfort and support.',
      price: 160,
      quantity: 1,
    ),
    Product(
      id: '5',
      name: 'Asics Gel-Kayano 27',
      category: 'Running',
      image: 'assets/sneakers/2.png',
      description:
      'Stability shoe with Gel technology for shock absorption and a secure fit.',
      price: 160,
      quantity: 1,
    ),
    Product(
      id: '6',
      name: 'Nike Air Force 1 Low',
      category: 'Classic',
      image: 'assets/sneakers/1.png',
      description:
      'Iconic sneaker known for its clean lines and timeless style, suitable for everyday wear.',
      price: 90,
      quantity: 1,
    ),
    Product(
      id: '7',
      name: 'Adidas Stan Smith',
      category: 'Classic',
      image: 'assets/sneakers/2.png',
      description:
      'Legendary tennis shoe with a minimalist design and perforated 3-Stripes.',
      price: 80,
      quantity: 1,
    ),
    Product(
      id: '8',
      name: 'Converse Chuck Taylor All Star',
      category: 'Classic',
      image: 'assets/sneakers/1.png',
      description:
      'Timeless silhouette with canvas upper and iconic star logo, perfect for casual wear.',
      price: 55,
      quantity: 1,
    ),
    Product(
      id: '9',
      name: 'Vans Old Skool',
      category: 'Skateboarding',
      image: 'assets/sneakers/2.png',
      description:
      'Skateboarding classic with durable canvas and suede upper, and signature sidestripe.',
      price: 60,
      quantity: 1,
    ),
    Product(
      id: '10',
      name: 'Puma RS-X3 Puzzle',
      category: 'Fashion',
      image: 'assets/sneakers/1.png',
      description:
      'Chunky sneaker with a retro-inspired design, featuring bold colors and layered details.',
      price: 120,
      quantity: 1,
    ),
    Product(
      id: '11',
      name: 'Reebok Club C 85',
      category: 'Classic',
      image: 'assets/sneakers/2.png',
      description:
      'Heritage tennis shoe with a soft leather upper and low-cut design for mobility.',
      price: 75,
      quantity: 1,
    ),
    Product(
      id: '12',
      name: 'Under Armour HOVR Sonic 4',
      category: 'Running',
      image: 'assets/sneakers/1.png',
      description:
      'Performance running shoe with UA HOVR technology for a responsive and cushioned ride.',
      price: 110,
      quantity: 1,
    ),
    Product(
      id: '13',
      name: 'Salomon Speedcross 5',
      category: 'Trail Running',
      image: 'assets/sneakers/2.png',
      description:
      'Aggressive grip trail running shoe with SensiFit for a secure and snug fit.',
      price: 130,
      quantity: 1,
    ),
    Product(
      id: '14',
      name: 'Brooks Ghost 13',
      category: 'Running',
      image: 'assets/sneakers/1.png',
      description:
      'Neutral running shoe with BioMoGo DNA and DNA Loft cushioning for smooth transitions.',
      price: 130,
      quantity: 1,
    ),
    Product(
      id: '15',
      name: 'Mizuno Wave Rider 24',
      category: 'Running',
      image: 'assets/sneakers/2.png',
      description:
      'Lightweight running shoe with Mizuno Wave technology for stability and cushioning.',
      price: 140,
      quantity: 1,
    ),
    Product(
      id: '16',
      name: 'Hoka One One Clifton 7',
      category: 'Running',
      image: 'assets/sneakers/1.png',
      description:
      'Maximalist running shoe with Hoka One One\'s Meta-Rocker technology for a smooth ride.',
      price: 130,
      quantity: 1,
    ),
    Product(
      id: '17',
      name: 'Nike Air Zoom Pegasus 38',
      category: 'Running',
      image: 'assets/sneakers/2.png',
      description:
      'Versatile running shoe with Zoom Air cushioning for responsiveness and comfort.',
      price: 120,
      quantity: 1,
    ),
    Product(
      id: '18',
      name: 'Adidas Yeezy Boost 350 V2',
      category: 'Fashion',
      image: 'assets/sneakers/1.png',
      description:
      'Fashion-forward sneaker designed by Kanye West, known for its distinctive style and comfort.',
      price: 220,
      quantity: 1,
    ),
    Product(
      id: '19',
      name: 'Jordan Retro 1 High OG',
      category: 'Basketball',
      image: 'assets/sneakers/2.png',
      description:
      'Classic basketball shoe with premium leather upper and Nike Air cushioning.',
      price: 170,
      quantity: 1,
    ),
    Product(
      id: '20',
      name: 'Saucony Kinvara 12',
      category: 'Running',
      image: 'assets/sneakers/1.png',
      description:
      'Lightweight running shoe with PWRRUN cushioning for a responsive and energized run.',
      price: 110,
      quantity: 1,
    ),
    Product(
      id: '21',
      name: 'Brooks Adrenaline GTS 21',
      category: 'Running',
      image: 'assets/sneakers/2.png',
      description:
      'Supportive running shoe with GuideRails support system for stability and comfort.',
      price: 130,
      quantity: 1,
    ),
    Product(
      id: '22',
      name: 'Nike Blazer Mid \'77 Vintage',
      category: 'Fashion',
      image: 'assets/sneakers/1.png',
      description:
      'Vintage-inspired sneaker with leather upper and classic design, perfect for casual wear.',
      price: 100,
      quantity: 1,
    ),
    Product(
      id: '23',
      name: 'Vans Sk8-Hi',
      category: 'Skateboarding',
      image: 'assets/sneakers/2.png',
      description:
      'High-top sneaker with durable suede and canvas upper, and padded collar for support.',
      price: 75,
      quantity: 1,
    ),
    Product(
      id: '24',
      name: 'Converse Chuck 70',
      category: 'Classic',
      image: 'assets/sneakers/1.png',
      description:
      'Premium version of the classic Chuck Taylor All Star with enhanced cushioning and craftsmanship.',
      price: 85,
      quantity: 1,
    ),
    Product(
      id: '25',
      name: 'Asics Gel-Nimbus 23',
      category: 'Running',
      image: 'assets/sneakers/2.png',
      description:
      'High-mileage running shoe with GEL technology for shock absorption and comfort.',
      price: 150,
      quantity: 1,
    ),
    Product(
      id: '26',
      name: 'The North Face Apex Bionic 2',
      category: 'Outdoor',
      image: 'assets/jackets/1.png',
      description: 'Windproof soft shell jacket with TNF Apex ClimateBlock fabric for cold weather protection.',
      price: 150,
      quantity: 1,
    ),
    Product(
      id: '27',
      name: 'Patagonia Nano Puff Jacket',
      category: 'Outdoor',
      image: 'assets/jackets/2.png',
      description: 'Lightweight, water-resistant jacket with synthetic insulation for warmth even when wet.',
      price: 199,
      quantity: 1,
    ),
    Product(
      id: '28',
      name: 'Arc\'teryx Atom LT Hoody',
      category: 'Outdoor',
      image: 'assets/jackets/3.png',
      description: 'Versatile insulated jacket with Coreloft insulation and breathable side panels.',
      price: 259,
      quantity: 1,
    ),
    Product(
      id: '29',
      name: 'Columbia Steens Mountain Fleece',
      category: 'Casual',
      image: 'assets/jackets/4.png',
      description: 'Classic full-zip fleece jacket with soft polyester fabric for lightweight warmth.',
      price: 45,
      quantity: 1,
    ),
    Product(
      id: '30',
      name: 'Arc\'teryx Beta AR Jacket',
      category: 'Outdoor',
      image: 'assets/jackets/5.png',
      description: 'Waterproof and breathable Gore-Tex Pro jacket for severe weather conditions.',
      price: 649,
      quantity: 1,
    ),
    Product(
      id: '31',
      name: 'Canada Goose Expedition Parka',
      category: 'Winter',
      image: 'assets/jackets/1.png',
      description: 'Extreme weather parka with Arctic Tech fabric and down insulation for ultimate warmth.',
      price: 995,
      quantity: 1,
    ),
    Product(
      id: '32',
      name: 'Burberry Kensington Trench Coat',
      category: 'Classic',
      image: 'assets/jackets/2.png',
      description: 'Iconic double-breasted trench coat with cotton gabardine fabric and signature check lining.',
      price: 1790,
      quantity: 1,
    ),
    Product(
      id: '33',
      name: 'Nike Sportswear Windrunner',
      category: 'Athletic',
      image: 'assets/jackets/3.png',
      description: 'Lightweight, water-resistant jacket with iconic chevron design for sporty style.',
      price: 100,
      quantity: 1,
    ),
    Product(
      id: '34',
      name: 'Helly Hansen Crew Midlayer Jacket',
      category: 'Sailing',
      image: 'assets/jackets/4.png',
      description: 'Waterproof and breathable sailing jacket with Helly Tech Protection and fleece lining.',
      price: 160,
      quantity: 1,
    ),
    Product(
      id: '35',
      name: 'Armani Exchange Puffer Jacket',
      category: 'Fashion',
      image: 'assets/jackets/5.png',
      description: 'Stylish puffer jacket with quilted design and down fill for warmth and comfort.',
      price: 250,
      quantity: 1,
    ),
    Product(
      id: '36',
      name: 'Columbia Watertight II Rain Jacket',
      category: 'Outdoor',
      image: 'assets/jackets/1.png',
      description: 'Lightweight rain jacket with Omni-Tech waterproof fabric and breathable mesh lining.',
      price: 75,
      quantity: 1,
    ),
    Product(
      id: '37',
      name: 'Carhartt Active Jacket',
      category: 'Workwear',
      image: 'assets/jackets/2.png',
      description: 'Durable work jacket with quilted flannel lining and triple-stitched main seams.',
      price: 99,
      quantity: 1,
    ),
    Product(
      id: '38',
      name: 'Patagonia Better Sweater Jacket',
      category: 'Casual',
      image: 'assets/jackets/3.png',
      description: 'Midweight fleece jacket with sweater-knit face and soft fleece interior for warmth.',
      price: 139,
      quantity: 1,
    ),
    Product(
      id: '39',
      name: 'Marmot PreCip Eco Jacket',
      category: 'Outdoor',
      image: 'assets/jackets/4.png',
      description: 'Lightweight and packable rain jacket with NanoPro waterproof fabric and pit zips for ventilation.',
      price: 99,
      quantity: 1,
    ),
    Product(
      id: '40',
      name: 'The North Face Denali 2 Jacket',
      category: 'Outdoor',
      image: 'assets/jackets/5.png',
      description: 'Classic fleece jacket with recycled polyester fabric and abrasion-resistant panels.',
      price: 179,
      quantity: 1,
    ),
    Product(
      id: '41',
      name: 'Columbia Glennaker Lake Rain Jacket',
      category: 'Outdoor',
      image: 'assets/jackets/1.png',
      description: 'Waterproof rain jacket with Hydroplus fabric and stow-away hood.',
      price: 49,
      quantity: 1,
    ),
    Product(
      id: '42',
      name: 'Canada Goose Chilliwack Bomber',
      category: 'Winter',
      image: 'assets/jackets/2.png',
      description: 'Heavy-duty bomber jacket with Arctic Tech fabric and down fill for warmth in extreme cold.',
      price: 850,
      quantity: 1,
    ),
    Product(
      id: '43',
      name: 'Barbour Ashby Wax Jacket',
      category: 'Classic',
      image: 'assets/jackets/3.png',
      description: 'Wax cotton jacket with tartan lining and weatherproof protection for timeless style.',
      price: 415,
      quantity: 1,
    ),
    Product(
      id: '44',
      name: 'Arc\'teryx Atom AR Hoody',
      category: 'Outdoor',
      image: 'assets/jackets/4.png',
      description: 'Versatile insulated jacket with Coreloft insulation and breathable side panels.',
      price: 299,
      quantity: 1,
    ),
    Product(
      id: '45',
      name: 'Moncler Maya Puffer Jacket',
      category: 'Fashion',
      image: 'assets/jackets/5.png',
      description: 'Luxury puffer jacket with down fill and signature quilted design.',
      price: 1450,
      quantity: 1,
    ),
    Product(
      id: '46',
      name: 'Tommy Hilfiger Packable Down Jacket',
      category: 'Casual',
      image: 'assets/jackets/1.png',
      description: 'Lightweight down jacket with stand collar and packable design for travel convenience.',
      price: 129,
      quantity: 1,
    ),
    Product(
      id: '47',
      name: 'Nike Tech Fleece Windrunner',
      category: 'Athletic',
      image: 'assets/jackets/2.png',
      description: 'Modern take on the classic Windrunner jacket with lightweight fleece fabric and articulated sleeves.',
      price: 130,
      quantity: 1,
    ),
    Product(
      id: '48',
      name: 'Arc\'teryx Beta SL Hybrid Jacket',
      category: 'Outdoor',
      image: 'assets/jackets/3.png',
      description: 'Lightweight and packable waterproof jacket with Gore-Tex protection and enhanced breathability.',
      price: 399,
      quantity: 1,
    ),
    Product(
      id: '49',
      name: 'Mountain Hardwear Ghost Whisperer/2',
      category: 'Outdoor',
      image: 'assets/jackets/4.png',
      description: 'Ultra-light down jacket with 800-fill goose down and water-resistant Q.Shield technology.',
      price: 325,
      quantity: 1,
    ),
    Product(
      id: '50',
      name: 'Arc\'teryx Cerium LT Hoody',
      category: 'Outdoor',
      image: 'assets/jackets/5.png',
      description: 'Lightweight down jacket with strategic placement of synthetic insulation for warmth and packability.',
      price: 379,
      quantity: 1,
    ),
    Product(
      id: '51',
      name: 'Apple MacBook Air M1',
      category: 'Ultrabook',
      image: 'assets/laptops/1.png',
      description:
      'Apple Silicon M1 chip with 8-core CPU and 7-core GPU, 13.3-inch Retina display, 256GB SSD storage.',
      price: 999,
      quantity: 1,
    ),
    Product(
      id: '52',
      name: 'Dell XPS 13',
      category: 'Ultrabook',
      image: 'assets/laptops/2.png',
      description:
      'Intel Core i7-1185G7, 13.4-inch 4K UHD+ touchscreen, 16GB RAM, 512GB SSD, Intel Iris Xe Graphics.',
      price: 1599,
      quantity: 1,
    ),
    Product(
      id: '53',
      name: 'HP Spectre x360 14',
      category: 'Convertible',
      image: 'assets/laptops/3.png',
      description:
      'Intel Core i7-1165G7, 13.5-inch OLED touch display, 16GB RAM, 1TB SSD, Intel Iris Xe Graphics.',
      price: 1499,
      quantity: 1,
    ),
    Product(
      id: '54',
      name: 'Lenovo ThinkPad X1 Carbon Gen 9',
      category: 'Business',
      image: 'assets/laptops/4.png',
      description:
      'Intel Core i7-1165G7, 14-inch 4K UHD+ display, 16GB RAM, 1TB SSD, Intel Iris Xe Graphics.',
      price: 1899,
      quantity: 1,
    ),
    Product(
      id: '55',
      name: 'ASUS ROG Zephyrus G14',
      category: 'Gaming',
      image: 'assets/laptops/5.png',
      description:
      'AMD Ryzen 9 5900HS, 14-inch QHD 120Hz display, 16GB RAM, 1TB SSD, NVIDIA GeForce RTX 3060.',
      price: 1799,
      quantity: 1,
    ),
    Product(
      id: '56',
      name: 'Acer Swift 5',
      category: 'Ultrabook',
      image: 'assets/laptops/1.png',
      description:
      'Intel Core i7-1165G7, 14-inch Full HD touchscreen, 16GB RAM, 1TB NVMe SSD, Intel Iris Xe Graphics.',
      price: 1099,
      quantity: 1,
    ),
    Product(
      id: '57',
      name: 'Microsoft Surface Laptop 4',
      category: 'Ultrabook',
      image: 'assets/laptops/2.png',
      description:
      'Intel Core i7-1185G7, 15-inch PixelSense touchscreen, 16GB RAM, 512GB SSD, Intel Iris Xe Graphics.',
      price: 1699,
      quantity: 1,
    ),
    Product(
      id: '58',
      name: 'Razer Blade 15',
      category: 'Gaming',
      image: 'assets/laptops/3.png',
      description:
      'Intel Core i7-10750H, 15.6-inch Full HD 144Hz display, 16GB RAM, 512GB SSD, NVIDIA GeForce RTX 3070.',
      price: 1999,
      quantity: 1,
    ),
    Product(
      id: '59',
      name: 'Samsung Galaxy Book Pro 360',
      category: 'Convertible',
      image: 'assets/laptops/4.png',
      description:
      'Intel Core i7-1165G7, 15.6-inch Super AMOLED touchscreen, 16GB RAM, 1TB NVMe SSD, Intel Iris Xe Graphics.',
      price: 1499,
      quantity: 1,
    ),
    Product(
      id: '60',
      name: 'HP Envy 15',
      category: 'Ultrabook',
      image: 'assets/laptops/5.png',
      description:
      'Intel Core i7-1165G7, 15.6-inch 4K UHD touchscreen, 16GB RAM, 1TB SSD, NVIDIA GeForce GTX 1650 Ti.',
      price: 1599,
      quantity: 1,
    ),
    Product(
      id: '61',
      name: 'Alienware m15 R5',
      category: 'Gaming',
      image: 'assets/laptops/1.png',
      description:
      'AMD Ryzen 9 5900HX, 15.6-inch QHD 240Hz display, 32GB RAM, 2TB SSD, NVIDIA GeForce RTX 3070.',
      price: 2599,
      quantity: 1,
    ),
    Product(
      id: '62',
      name: 'Apple MacBook Pro 14-inch M1 Pro',
      category: 'Professional',
      image: 'assets/laptops/2.png',
      description:
      'Apple Silicon M1 Pro chip with 10-core CPU and 16-core GPU, 14.2-inch Liquid Retina XDR display, 1TB SSD storage.',
      price: 1999,
      quantity: 1,
    ),
    Product(
      id: '63',
      name: 'Dell Latitude 9520',
      category: 'Business',
      image: 'assets/laptops/3.png',
      description:
      'Intel Core i7-1185G7, 15-inch Full HD touchscreen, 32GB RAM, 1TB SSD, Intel Iris Xe Graphics.',
      price: 2399,
      quantity: 1,
    ),
    Product(
      id: '64',
      name: 'Lenovo Legion 5 Pro',
      category: 'Gaming',
      image: 'assets/laptops/4.png',
      description:
      'AMD Ryzen 7 5800H, 16-inch QHD 165Hz display, 32GB RAM, 1TB SSD, NVIDIA GeForce RTX 3070.',
      price: 1799,
      quantity: 1,
    ),
    Product(
      id: '65',
      name: 'ASUS ZenBook Duo 14',
      category: 'Dual Screen',
      image: 'assets/laptops/5.png',
      description:
      'Intel Core i7-1165G7, 14-inch Full HD touchscreen and secondary 12.6-inch ScreenPad Plus display, 16GB RAM, 1TB SSD, Intel Iris Xe Graphics.',
      price: 1699,
      quantity: 1,
    ),
    Product(
      id: '66',
      name: 'Acer Predator Helios 300',
      category: 'Gaming',
      image: 'assets/laptops/1.png',
      description:
      'Intel Core i7-11800H, 15.6-inch Full HD 144Hz display, 16GB RAM, 512GB NVMe SSD, NVIDIA GeForce RTX 3060.',
      price: 1399,
      quantity: 1,
    ),
    Product(
      id: '67',
      name: 'Microsoft Surface Laptop Studio',
      category: 'Convertible',
      image: 'assets/laptops/2.png',
      description:
      'Intel Core i7-11370H, 14.4-inch PixelSense touchscreen with Surface Pen support, 32GB RAM, 1TB SSD, NVIDIA GeForce RTX 3050 Ti.',
      price: 2499,
      quantity: 1,
    ),
    Product(
      id: '68',
      name: 'Razer Blade Stealth 13',
      category: 'Ultrabook',
      image: 'assets/laptops/3.png',
      description:
      'Intel Core i7-1165G7, 13.3-inch Full HD touchscreen, 16GB RAM, 512GB SSD, NVIDIA GeForce GTX 1650 Ti Max-Q.',
      price: 1499,
      quantity: 1,
    ),
    Product(
      id: '69',
      name: 'Samsung Galaxy Book Flex 2',
      category: 'Convertible',
      image: 'assets/laptops/4.png',
      description:
      'Intel Core i7-1165G7, 15.6-inch QLED touchscreen with S Pen support, 16GB RAM, 1TB NVMe SSD, Intel Iris Xe Graphics.',
      price: 1399,
      quantity: 1,
    ),
    Product(
      id: '70',
      name: 'HP Omen 15',
      category: 'Gaming',
      image: 'assets/laptops/5.png',
      description:
      'Intel Core i7-11800H, 15.6-inch Full HD 144Hz display, 16GB RAM, 1TB SSD, NVIDIA GeForce RTX 3070.',
      price: 1799,
      quantity: 1,
    ),
    Product(
      id: '71',
      name: 'Acer Chromebook Spin 713',
      category: 'Chromebook',
      image: 'assets/laptops/1.png',
      description:
      'Intel Core i5-1135G7, 13.5-inch 2K VertiView touchscreen, 8GB RAM, 256GB NVMe SSD, Intel Iris Xe Graphics.',
      price: 629,
      quantity: 1,
    ),
    Product(
      id: '72',
      name: 'Lenovo Yoga 9i',
      category: 'Convertible',
      image: 'assets/laptops/2.png',
      description:
      'Intel Core i7-1185G7, 14-inch 4K UHD touchscreen with Dolby Vision HDR, 16GB RAM, 1TB SSD, Intel Iris Xe Graphics.',
      price: 1599,
      quantity: 1,
    ),
    Product(
      id: '73',
      name: 'ASUS ROG Strix G15',
      category: 'Gaming',
      image: 'assets/laptops/3.png',
      description:
      'AMD Ryzen 9 5900HX, 15.6-inch Full HD 300Hz display, 32GB RAM, 1TB SSD, NVIDIA GeForce RTX 3080.',
      price: 2299,
      quantity: 1,
    ),
    Product(
      id: '74',
      name: 'Dell Inspiron 14 5000',
      category: 'Ultrabook',
      image: 'assets/laptops/4.png',
      description:
      'Intel Core i7-1165G7, 14-inch Full HD touchscreen, 16GB RAM, 512GB SSD, Intel Iris Xe Graphics.',
      price: 999,
      quantity: 1,
    ),
    Product(
      id: '75',
      name: 'Microsoft Surface Pro 8',
      category: 'Tablet PC',
      image: 'assets/laptops/5.png',
      description:
      'Intel Core i7-1185G7, 13-inch PixelSense touchscreen, 16GB RAM, 512GB SSD, Intel Iris Xe Graphics.',
      price: 1299,
      quantity: 1,
    ),
    Product(
      id: '76',
      name: 'Apple iPhone 13 Pro',
      category: 'Smartphone',
      image: 'assets/phones/1.png',
      description:
      'Super Retina XDR display, A15 Bionic chip, Pro camera system with 12MP Ultra Wide, Wide, and Telephoto cameras, ProRAW, Night mode, 5G capable.',
      price: 999,
      quantity: 1,
    ),
    Product(
      id: '77',
      name: 'Samsung Galaxy S22 Ultra',
      category: 'Smartphone',
      image: 'assets/phones/2.png',
      description:
      '6.8-inch Dynamic AMOLED 2X display, Snapdragon 8 Gen 1 or Exynos 2200 chip, quad camera setup with 108MP main sensor, 5000mAh battery, S Pen support.',
      price: 1199,
      quantity: 1,
    ),
    Product(
      id: '78',
      name: 'Google Pixel 6 Pro',
      category: 'Smartphone',
      image: 'assets/phones/3.png',
      description:
      '6.7-inch Fluid AMOLED display, Google Tensor chip, 50MP main sensor, 12MP ultra-wide, 48MP telephoto, 5000mAh battery, 5G capable.',
      price: 899,
      quantity: 1,
    ),
    Product(
      id: '79',
      name: 'OnePlus 10 Pro',
      category: 'Smartphone',
      image: 'assets/phones/4.png',
      description:
      '6.7-inch Fluid AMOLED display, Snapdragon 8 Gen 1 chip, triple camera system with 50MP main sensor, 5000mAh battery, Warp Charge 65T.',
      price: 899,
      quantity: 1,
    ),
    Product(
      id: '80',
      name: 'Apple iPhone SE (2022)',
      category: 'Smartphone',
      image: 'assets/phones/5.png',
      description:
      '4.7-inch Retina HD display, A15 Bionic chip, single 12MP Wide camera, Touch ID, 5G capable, compact design.',
      price: 429,
      quantity: 1,
    ),
    Product(
      id: '81',
      name: 'Xiaomi Mi 12 Ultra',
      category: 'Smartphone',
      image: 'assets/phones/1.png',
      description:
      '6.8-inch AMOLED display, Snapdragon 8 Gen 1 chip, quad camera setup with 200MP main sensor, 5000mAh battery, 120W fast charging.',
      price: 1099,
      quantity: 1,
    ),
    Product(
      id: '82',
      name: 'Sony Xperia 1 III',
      category: 'Smartphone',
      image: 'assets/phones/2.png',
      description:
      '6.5-inch 4K OLED display, Snapdragon 888 chip, triple camera system with 12MP main sensor, 4500mAh battery, 5G capable, 120Hz refresh rate.',
      price: 1299,
      quantity: 1,
    ),
    Product(
      id: '83',
      name: 'Samsung Galaxy Z Fold 3',
      category: 'Foldable',
      image: 'assets/phones/3.png',
      description:
      '7.6-inch Dynamic AMOLED 2X main display, Snapdragon 888 chip, triple camera system, 4400mAh battery, S Pen support, water resistant.',
      price: 1799,
      quantity: 1,
    ),
    Product(
      id: '84',
      name: 'Xiaomi Redmi Note 11 Pro+',
      category: 'Smartphone',
      image: 'assets/phones/4.png',
      description:
      '6.67-inch AMOLED display, Snapdragon 695 chip, quad camera setup with 108MP main sensor, 5000mAh battery, 67W fast charging.',
      price: 499,
      quantity: 1,
    ),
    Product(
      id: '85',
      name: 'Google Pixel 5a 5G',
      category: 'Smartphone',
      image: 'assets/phones/5.png',
      description:
      '6.34-inch OLED display, Snapdragon 765G chip, dual camera system with 12.2MP main sensor, 4680mAh battery, 5G capable.',
      price: 449,
      quantity: 1,
    ),
    Product(
      id: '86',
      name: 'Motorola Edge 30 Ultra',
      category: 'Smartphone',
      image: 'assets/phones/1.png',
      description:
      '6.7-inch OLED display, Snapdragon 8 Gen 1 chip, triple camera system with 50MP main sensor, 5000mAh battery, 60W fast charging.',
      price: 899,
      quantity: 1,
    ),
    Product(
      id: '87',
      name: 'Apple iPhone 13 mini',
      category: 'Smartphone',
      image: 'assets/phones/2.png',
      description:
      'Super Retina XDR display, A15 Bionic chip, dual camera system with 12MP Wide and Ultra Wide cameras, 5G capable, compact design.',
      price: 699,
      quantity: 1,
    ),
    Product(
      id: '88',
      name: 'OnePlus 9 Pro',
      category: 'Smartphone',
      image: 'assets/phones/3.png',
      description:
      '6.7-inch Fluid AMOLED display, Snapdragon 888 chip, quad camera system with 48MP main sensor, 4500mAh battery, Warp Charge 65T.',
      price: 969,
      quantity: 1,
    ),
    Product(
      id: '89',
      name: 'Samsung Galaxy A53 5G',
      category: 'Smartphone',
      image: 'assets/phones/4.png',
      description:
      '6.5-inch Super AMOLED display, Snapdragon 778G chip, quad camera setup with 64MP main sensor, 4500mAh battery, 25W fast charging.',
      price: 449,
      quantity: 1,
    ),
    Product(
      id: '90',
      name: 'Xiaomi Poco X4 Pro 5G',
      category: 'Smartphone',
      image: 'assets/phones/5.png',
      description:
      '6.67-inch AMOLED display, Snapdragon 695 chip, quad camera setup with 108MP main sensor, 5000mAh battery, 67W fast charging.',
      price: 399,
      quantity: 1,
    ),
    Product(
      id: '91',
      name: 'Sony Xperia 5 III',
      category: 'Smartphone',
      image: 'assets/phones/1.png',
      description:
      '6.1-inch OLED display, Snapdragon 888 chip, triple camera system with 12MP main sensor, 4500mAh battery, 5G capable, 120Hz refresh rate.',
      price: 1099,
      quantity: 1,
    ),
    Product(
      id: '92',
      name: 'Realme GT 2 Pro',
      category: 'Smartphone',
      image: 'assets/phones/2.png',
      description:
      '6.7-inch Super AMOLED display, Snapdragon 8 Gen 1 chip, triple camera system with 50MP main sensor, 5000mAh battery, 65W fast charging.',
      price: 899,
      quantity: 1,
    ),
    Product(
      id: '93',
      name: 'Nokia X100',
      category: 'Smartphone',
      image: 'assets/phones/3.png',
      description:
      '6.67-inch IPS LCD display, Snapdragon 480 chip, quad camera setup with 48MP main sensor, 4470mAh battery, 18W fast charging.',
      price: 249,
      quantity: 1,
    ),
    Product(
      id: '94',
      name: 'LG Velvet 2 Pro 5G',
      category: 'Smartphone',
      image: 'assets/phones/4.png',
      description:
      '6.8-inch POLED display, Snapdragon 888 chip, triple camera system with 64MP main sensor, 4500mAh battery, 25W fast charging.',
      price: 599,
      quantity: 1,
    ),
    Product(
      id: '95',
      name: 'Motorola Moto G Stylus (2022)',
      category: 'Smartphone',
      image: 'assets/phones/5.png',
      description:
      '6.8-inch IPS LCD display, Snapdragon 678 chip, quad camera setup with 50MP main sensor, 5000mAh battery, 30W fast charging, built-in stylus.',
      price: 299,
      quantity: 1,
    ),
    Product(
      id: '96',
      name: 'Google Pixel 4a 5G',
      category: 'Smartphone',
      image: 'assets/phones/1.png',
      description:
      '6.2-inch OLED display, Snapdragon 765G chip, dual camera system with 12.2MP main sensor, 3885mAh battery, 5G capable.',
      price: 499,
      quantity: 1,
    ),
    Product(
      id: '97',
      name: 'Samsung Galaxy M52 5G',
      category: 'Smartphone',
      image: 'assets/phones/2.png',
      description:
      '6.7-inch Super AMOLED Plus display, Snapdragon 778G chip, triple camera setup with 64MP main sensor, 5000mAh battery, 25W fast charging.',
      price: 379,
      quantity: 1,
    ),
    Product(
      id: '98',
      name: 'Xiaomi Redmi Note 10 Pro',
      category: 'Smartphone',
      image: 'assets/phones/3.png',
      description:
      '6.67-inch Super AMOLED display, Snapdragon 732G chip, quad camera setup with 108MP main sensor, 5020mAh battery, 33W fast charging.',
      price: 279,
      quantity: 1,
    ),
    Product(
      id: '99',
      name: 'OnePlus Nord 2',
      category: 'Smartphone',
      image: 'assets/phones/4.png',
      description:
      '6.43-inch Fluid AMOLED display, MediaTek Dimensity 1200 AI chip, triple camera system with 50MP main sensor, 4500mAh battery, Warp Charge 65T.',
      price: 399,
      quantity: 1,
    ),
    Product(
      id: '100',
      name: 'Apple iPhone SE (2020)',
      category: 'Smartphone',
      image: 'assets/phones/5.png',
      description:
      '4.7-inch Retina HD display, A13 Bionic chip, single 12MP Wide camera, Touch ID, compact design.',
      price: 399,
      quantity: 1,
    ),
    Product(
      id: '101',
      name: 'Adidas Originals Trefoil Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/1.png',
      description:
      'Classic Adidas Originals Trefoil logo tee, made from 100% cotton for comfort and breathability.',
      price: 25,
      quantity: 1,
    ),
    Product(
      id: '102',
      name: 'Nike Sportswear Club Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/2.png',
      description:
      'Nike Sportswear Club tee with embroidered Nike logo, crafted from soft cotton jersey fabric.',
      price: 20,
      quantity: 1,
    ),
    Product(
      id: '103',
      name: 'Under Armour Men\'s Tech 2.0 Short Sleeve Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/3.png',
      description:
      'Under Armour Tech 2.0 tee featuring quick-drying, ultra-soft fabric for superior comfort during workouts.',
      price: 30,
      quantity: 1,
    ),
    Product(
      id: '104',
      name: 'Puma Essentials Logo Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/4.png',
      description:
      'Puma Essentials logo tee made from 100% cotton, featuring a classic crew neck design and Puma logo.',
      price: 22,
      quantity: 1,
    ),
    Product(
      id: '105',
      name: 'Levi\'s Men\'s Graphic Set-In Neck Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/5.png',
      description:
      'Levi\'s graphic tee with iconic Levi\'s logo print, made from soft and comfortable cotton jersey fabric.',
      price: 28,
      quantity: 1,
    ),
    Product(
      id: '106',
      name: 'Hanes Men\'s ComfortSoft Short Sleeve T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/1.png',
      description:
      'Hanes ComfortSoft tee with Tagless label for itch-free comfort, made from 100% preshrunk ComfortSoft cotton.',
      price: 15,
      quantity: 1,
    ),
    Product(
      id: '107',
      name: 'Fruit of the Loom Men\'s Crew T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/2.png',
      description:
      'Fruit of the Loom crew neck tee, made from 100% cotton for softness and durability, suitable for everyday wear.',
      price: 18,
      quantity: 1,
    ),
    Product(
      id: '108',
      name: 'Champion Classic Jersey Script Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/3.png',
      description:
      'Champion Classic Jersey tee featuring Champion script logo on the chest, made from ring-spun cotton for a softer feel.',
      price: 24,
      quantity: 1,
    ),
    Product(
      id: '109',
      name: 'Tommy Hilfiger Men\'s Flag Crew Neck Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/4.png',
      description:
      'Tommy Hilfiger crew neck tee with embroidered flag logo on chest, made from premium cotton jersey fabric.',
      price: 32,
      quantity: 1,
    ),
    Product(
      id: '110',
      name: 'Gap Essential Crewneck T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/5.png',
      description:
      'Gap Essential tee crafted from soft, premium jersey cotton for a comfortable fit and feel.',
      price: 19,
      quantity: 1,
    ),
    Product(
      id: '111',
      name: 'American Eagle Men\'s Heritage Pocket T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/1.png',
      description:
      'American Eagle Heritage tee with pocket, made from soft cotton jersey and garment-dyed for a vintage look.',
      price: 26,
      quantity: 1,
    ),
    Product(
      id: '112',
      name: 'Abercrombie & Fitch Men\'s Short Sleeve Logo Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/2.png',
      description:
      'Abercrombie & Fitch logo tee featuring printed logo graphic on soft cotton jersey fabric.',
      price: 29,
      quantity: 1,
    ),
    Product(
      id: '113',
      name: 'Ralph Lauren Men\'s Classic Fit Crewneck T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/3.png',
      description:
      'Ralph Lauren Classic Fit tee with signature embroidered pony logo, made from premium cotton jersey.',
      price: 35,
      quantity: 1,
    ),
    Product(
      id: '114',
      name: 'Vans Classic T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/4.png',
      description:
      'Vans Classic tee with Vans logo print, made from 100% ringspun cotton for a soft feel and durability.',
      price: 25,
      quantity: 1,
    ),
    Product(
      id: '115',
      name: 'Calvin Klein Men\'s Short Sleeve Logo T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/5.png',
      description:
      'Calvin Klein logo tee featuring printed CK logo on chest, made from soft and comfortable cotton jersey fabric.',
      price: 27,
      quantity: 1,
    ),
    Product(
      id: '116',
      name: 'Lacoste Men\'s Crew Neck Pima Cotton Jersey T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/1.png',
      description:
      'Lacoste crew neck tee made from luxurious Pima cotton jersey, featuring iconic Lacoste crocodile logo.',
      price: 39,
      quantity: 1,
    ),
    Product(
      id: '117',
      name: 'Aéropostale Solid Crew Neck T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/2.png',
      description:
      'Aéropostale solid crew neck tee, made from soft and breathable cotton for everyday comfort.',
      price: 20,
      quantity: 1,
    ),
    Product(
      id: '118',
      name: 'Guess Men\'s Short Sleeve Triangle Logo T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/3.png',
      description:
      'Guess Triangle Logo tee featuring printed logo graphic on chest, made from comfortable cotton jersey.',
      price: 30,
      quantity: 1,
    ),
    Product(
      id: '119',
      name: 'Hollister Men\'s Must-Have Crew T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/4.png',
      description:
      'Hollister Must-Have tee with logo graphic, crafted from soft cotton jersey for all-day comfort.',
      price: 22,
      quantity: 1,
    ),
    Product(
      id: '120',
      name: 'Superdry Men\'s Vintage Logo Tri T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/5.png',
      description:
      'Superdry Vintage Logo Tri tee featuring textured logo print on chest, made from soft cotton fabric.',
      price: 32,
      quantity: 1,
    ),
    Product(
      id: '121',
      name: 'Diesel Men\'s T-Diego-Division Logo T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/1.png',
      description:
      'Diesel T-Diego-Division Logo tee with logo graphic, made from soft cotton jersey for a comfortable fit.',
      price: 35,
      quantity: 1,
    ),
    Product(
      id: '122',
      name: 'Gap Essential V-Neck T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/2.png',
      description:
      'Gap Essential V-Neck tee crafted from soft, premium jersey cotton for a comfortable and relaxed fit.',
      price: 18,
      quantity: 1,
    ),
    Product(
      id: '123',
      name: 'Tommy Jeans Men\'s T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/3.png',
      description:
      'Tommy Jeans Essential Flag tee with Tommy Jeans logo and flag embroidery, made from soft cotton jersey.',
      price: 29,
      quantity: 1,
    ),
    Product(
      id: '124',
      name: 'American Eagle Men\'s AE Surf Co. Graphic T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/4.png',
      description:
      'American Eagle AE Surf Co. Graphic tee with printed graphic on chest, made from soft cotton jersey.',
      price: 25,
      quantity: 1,
    ),
    Product(
      id: '125',
      name: 'Abercrombie & Fitch Men\'s Short Sleeve Henley',
      category: 'T-Shirt',
      image: 'assets/tshirts/5.png',
      description:
      'Abercrombie & Fitch Henley tee with button placket and logo embroidery, made from soft slub cotton.',
      price: 34,
      quantity: 1,
    ),
  ];


  static List<Product> sneakers = [
    Product(
      id: '1',
      name: 'Nike Air Max 200',
      category: 'Trending',
      image: 'assets/sneakers/1.png',
      description:
      'Clean lines, versatile and timeless, the best quality fabric with sustainable air cushion which provides day long comfort.',
      price: 700,
      quantity: 1,
    ),
    Product(
      id: '2',
      name: 'Adidas Ultraboost 21',
      category: 'Running',
      image: 'assets/sneakers/2.png',
      description:
      'Designed for high performance running, featuring Boost technology for ultimate energy return.',
      price: 180,
      quantity: 1,
    ),
    Product(
      id: '3',
      name: 'New Balance Fresh Foam 1080v11',
      category: 'Running',
      image: 'assets/sneakers/2.png',
      description:
      'Engineered with a Fresh Foam midsole, providing luxurious cushioning for the ultimate ride.',
      price: 150,
      quantity: 1,
    ),
    Product(
      id: '4',
      name: 'Nike React Infinity Run Flyknit',
      category: 'Running',
      image: 'assets/sneakers/1.png',
      description:
      'Innovative design with React foam and Flyknit upper for lightweight comfort and support.',
      price: 160,
      quantity: 1,
    ),
    Product(
      id: '5',
      name: 'Asics Gel-Kayano 27',
      category: 'Running',
      image: 'assets/sneakers/2.png',
      description:
      'Stability shoe with Gel technology for shock absorption and a secure fit.',
      price: 160,
      quantity: 1,
    ),
    Product(
      id: '6',
      name: 'Nike Air Force 1 Low',
      category: 'Classic',
      image: 'assets/sneakers/1.png',
      description:
      'Iconic sneaker known for its clean lines and timeless style, suitable for everyday wear.',
      price: 90,
      quantity: 1,
    ),
    Product(
      id: '7',
      name: 'Adidas Stan Smith',
      category: 'Classic',
      image: 'assets/sneakers/2.png',
      description:
      'Legendary tennis shoe with a minimalist design and perforated 3-Stripes.',
      price: 80,
      quantity: 1,
    ),
    Product(
      id: '8',
      name: 'Converse Chuck Taylor All Star',
      category: 'Classic',
      image: 'assets/sneakers/1.png',
      description:
      'Timeless silhouette with canvas upper and iconic star logo, perfect for casual wear.',
      price: 55,
      quantity: 1,
    ),
    Product(
      id: '9',
      name: 'Vans Old Skool',
      category: 'Skateboarding',
      image: 'assets/sneakers/2.png',
      description:
      'Skateboarding classic with durable canvas and suede upper, and signature sidestripe.',
      price: 60,
      quantity: 1,
    ),
    Product(
      id: '10',
      name: 'Puma RS-X3 Puzzle',
      category: 'Fashion',
      image: 'assets/sneakers/1.png',
      description:
      'Chunky sneaker with a retro-inspired design, featuring bold colors and layered details.',
      price: 120,
      quantity: 1,
    ),
    Product(
      id: '11',
      name: 'Reebok Club C 85',
      category: 'Classic',
      image: 'assets/sneakers/2.png',
      description:
      'Heritage tennis shoe with a soft leather upper and low-cut design for mobility.',
      price: 75,
      quantity: 1,
    ),
    Product(
      id: '12',
      name: 'Under Armour HOVR Sonic 4',
      category: 'Running',
      image: 'assets/sneakers/1.png',
      description:
      'Performance running shoe with UA HOVR technology for a responsive and cushioned ride.',
      price: 110,
      quantity: 1,
    ),
    Product(
      id: '13',
      name: 'Salomon Speedcross 5',
      category: 'Trail Running',
      image: 'assets/sneakers/2.png',
      description:
      'Aggressive grip trail running shoe with SensiFit for a secure and snug fit.',
      price: 130,
      quantity: 1,
    ),
    Product(
      id: '14',
      name: 'Brooks Ghost 13',
      category: 'Running',
      image: 'assets/sneakers/1.png',
      description:
      'Neutral running shoe with BioMoGo DNA and DNA Loft cushioning for smooth transitions.',
      price: 130,
      quantity: 1,
    ),
    Product(
      id: '15',
      name: 'Mizuno Wave Rider 24',
      category: 'Running',
      image: 'assets/sneakers/2.png',
      description:
      'Lightweight running shoe with Mizuno Wave technology for stability and cushioning.',
      price: 140,
      quantity: 1,
    ),
    Product(
      id: '16',
      name: 'Hoka One One Clifton 7',
      category: 'Running',
      image: 'assets/sneakers/1.png',
      description:
      'Maximalist running shoe with Hoka One One\'s Meta-Rocker technology for a smooth ride.',
      price: 130,
      quantity: 1,
    ),
    Product(
      id: '17',
      name: 'Nike Air Zoom Pegasus 38',
      category: 'Running',
      image: 'assets/sneakers/2.png',
      description:
      'Versatile running shoe with Zoom Air cushioning for responsiveness and comfort.',
      price: 120,
      quantity: 1,
    ),
    Product(
      id: '18',
      name: 'Adidas Yeezy Boost 350 V2',
      category: 'Fashion',
      image: 'assets/sneakers/1.png',
      description:
      'Fashion-forward sneaker designed by Kanye West, known for its distinctive style and comfort.',
      price: 220,
      quantity: 1,
    ),
    Product(
      id: '19',
      name: 'Jordan Retro 1 High OG',
      category: 'Basketball',
      image: 'assets/sneakers/2.png',
      description:
      'Classic basketball shoe with premium leather upper and Nike Air cushioning.',
      price: 170,
      quantity: 1,
    ),
    Product(
      id: '20',
      name: 'Saucony Kinvara 12',
      category: 'Running',
      image: 'assets/sneakers/1.png',
      description:
      'Lightweight running shoe with PWRRUN cushioning for a responsive and energized run.',
      price: 110,
      quantity: 1,
    ),
    Product(
      id: '21',
      name: 'Brooks Adrenaline GTS 21',
      category: 'Running',
      image: 'assets/sneakers/2.png',
      description:
      'Supportive running shoe with GuideRails support system for stability and comfort.',
      price: 130,
      quantity: 1,
    ),
    Product(
      id: '22',
      name: 'Nike Blazer Mid \'77 Vintage',
      category: 'Fashion',
      image: 'assets/sneakers/1.png',
      description:
      'Vintage-inspired sneaker with leather upper and classic design, perfect for casual wear.',
      price: 100,
      quantity: 1,
    ),
    Product(
      id: '23',
      name: 'Vans Sk8-Hi',
      category: 'Skateboarding',
      image: 'assets/sneakers/2.png',
      description:
      'High-top sneaker with durable suede and canvas upper, and padded collar for support.',
      price: 75,
      quantity: 1,
    ),
    Product(
      id: '24',
      name: 'Converse Chuck 70',
      category: 'Classic',
      image: 'assets/sneakers/1.png',
      description:
      'Premium version of the classic Chuck Taylor All Star with enhanced cushioning and craftsmanship.',
      price: 85,
      quantity: 1,
    ),
    Product(
      id: '25',
      name: 'Asics Gel-Nimbus 23',
      category: 'Running',
      image: 'assets/sneakers/2.png',
      description:
      'High-mileage running shoe with GEL technology for shock absorption and comfort.',
      price: 150,
      quantity: 1,
    ),
  ];
  static List<Product> jackets = [
    Product(
      id: '26',
      name: 'The North Face Apex Bionic 2',
      category: 'Outdoor',
      image: 'assets/jackets/1.png',
      description: 'Windproof soft shell jacket with TNF Apex ClimateBlock fabric for cold weather protection.',
      price: 150,
      quantity: 1,
    ),
    Product(
      id: '27',
      name: 'Patagonia Nano Puff Jacket',
      category: 'Outdoor',
      image: 'assets/jackets/2.png',
      description: 'Lightweight, water-resistant jacket with synthetic insulation for warmth even when wet.',
      price: 199,
      quantity: 1,
    ),
    Product(
      id: '28',
      name: 'Arc\'teryx Atom LT Hoody',
      category: 'Outdoor',
      image: 'assets/jackets/3.png',
      description: 'Versatile insulated jacket with Coreloft insulation and breathable side panels.',
      price: 259,
      quantity: 1,
    ),
    Product(
      id: '29',
      name: 'Columbia Steens Mountain Fleece',
      category: 'Casual',
      image: 'assets/jackets/4.png',
      description: 'Classic full-zip fleece jacket with soft polyester fabric for lightweight warmth.',
      price: 45,
      quantity: 1,
    ),
    Product(
      id: '30',
      name: 'Arc\'teryx Beta AR Jacket',
      category: 'Outdoor',
      image: 'assets/jackets/5.png',
      description: 'Waterproof and breathable Gore-Tex Pro jacket for severe weather conditions.',
      price: 649,
      quantity: 1,
    ),
    Product(
      id: '31',
      name: 'Canada Goose Expedition Parka',
      category: 'Winter',
      image: 'assets/jackets/1.png',
      description: 'Extreme weather parka with Arctic Tech fabric and down insulation for ultimate warmth.',
      price: 995,
      quantity: 1,
    ),
    Product(
      id: '32',
      name: 'Burberry Kensington Trench Coat',
      category: 'Classic',
      image: 'assets/jackets/2.png',
      description: 'Iconic double-breasted trench coat with cotton gabardine fabric and signature check lining.',
      price: 1790,
      quantity: 1,
    ),
    Product(
      id: '33',
      name: 'Nike Sportswear Windrunner',
      category: 'Athletic',
      image: 'assets/jackets/3.png',
      description: 'Lightweight, water-resistant jacket with iconic chevron design for sporty style.',
      price: 100,
      quantity: 1,
    ),
    Product(
      id: '34',
      name: 'Helly Hansen Crew Midlayer Jacket',
      category: 'Sailing',
      image: 'assets/jackets/4.png',
      description: 'Waterproof and breathable sailing jacket with Helly Tech Protection and fleece lining.',
      price: 160,
      quantity: 1,
    ),
    Product(
      id: '35',
      name: 'Armani Exchange Puffer Jacket',
      category: 'Fashion',
      image: 'assets/jackets/5.png',
      description: 'Stylish puffer jacket with quilted design and down fill for warmth and comfort.',
      price: 250,
      quantity: 1,
    ),
    Product(
      id: '36',
      name: 'Columbia Watertight II Rain Jacket',
      category: 'Outdoor',
      image: 'assets/jackets/1.png',
      description: 'Lightweight rain jacket with Omni-Tech waterproof fabric and breathable mesh lining.',
      price: 75,
      quantity: 1,
    ),
    Product(
      id: '37',
      name: 'Carhartt Active Jacket',
      category: 'Workwear',
      image: 'assets/jackets/2.png',
      description: 'Durable work jacket with quilted flannel lining and triple-stitched main seams.',
      price: 99,
      quantity: 1,
    ),
    Product(
      id: '38',
      name: 'Patagonia Better Sweater Jacket',
      category: 'Casual',
      image: 'assets/jackets/3.png',
      description: 'Midweight fleece jacket with sweater-knit face and soft fleece interior for warmth.',
      price: 139,
      quantity: 1,
    ),
    Product(
      id: '39',
      name: 'Marmot PreCip Eco Jacket',
      category: 'Outdoor',
      image: 'assets/jackets/4.png',
      description: 'Lightweight and packable rain jacket with NanoPro waterproof fabric and pit zips for ventilation.',
      price: 99,
      quantity: 1,
    ),
    Product(
      id: '40',
      name: 'The North Face Denali 2 Jacket',
      category: 'Outdoor',
      image: 'assets/jackets/5.png',
      description: 'Classic fleece jacket with recycled polyester fabric and abrasion-resistant panels.',
      price: 179,
      quantity: 1,
    ),
    Product(
      id: '41',
      name: 'Columbia Glennaker Lake Rain Jacket',
      category: 'Outdoor',
      image: 'assets/jackets/1.png',
      description: 'Waterproof rain jacket with Hydroplus fabric and stow-away hood.',
      price: 49,
      quantity: 1,
    ),
    Product(
      id: '42',
      name: 'Canada Goose Chilliwack Bomber',
      category: 'Winter',
      image: 'assets/jackets/2.png',
      description: 'Heavy-duty bomber jacket with Arctic Tech fabric and down fill for warmth in extreme cold.',
      price: 850,
      quantity: 1,
    ),
    Product(
      id: '43',
      name: 'Barbour Ashby Wax Jacket',
      category: 'Classic',
      image: 'assets/jackets/3.png',
      description: 'Wax cotton jacket with tartan lining and weatherproof protection for timeless style.',
      price: 415,
      quantity: 1,
    ),
    Product(
      id: '44',
      name: 'Arc\'teryx Atom AR Hoody',
      category: 'Outdoor',
      image: 'assets/jackets/4.png',
      description: 'Versatile insulated jacket with Coreloft insulation and breathable side panels.',
      price: 299,
      quantity: 1,
    ),
    Product(
      id: '45',
      name: 'Moncler Maya Puffer Jacket',
      category: 'Fashion',
      image: 'assets/jackets/5.png',
      description: 'Luxury puffer jacket with down fill and signature quilted design.',
      price: 1450,
      quantity: 1,
    ),
    Product(
      id: '46',
      name: 'Tommy Hilfiger Packable Down Jacket',
      category: 'Casual',
      image: 'assets/jackets/1.png',
      description: 'Lightweight down jacket with stand collar and packable design for travel convenience.',
      price: 129,
      quantity: 1,
    ),
    Product(
      id: '47',
      name: 'Nike Tech Fleece Windrunner',
      category: 'Athletic',
      image: 'assets/jackets/2.png',
      description: 'Modern take on the classic Windrunner jacket with lightweight fleece fabric and articulated sleeves.',
      price: 130,
      quantity: 1,
    ),
    Product(
      id: '48',
      name: 'Arc\'teryx Beta SL Hybrid Jacket',
      category: 'Outdoor',
      image: 'assets/jackets/3.png',
      description: 'Lightweight and packable waterproof jacket with Gore-Tex protection and enhanced breathability.',
      price: 399,
      quantity: 1,
    ),
    Product(
      id: '49',
      name: 'Mountain Hardwear Ghost Whisperer/2',
      category: 'Outdoor',
      image: 'assets/jackets/4.png',
      description: 'Ultra-light down jacket with 800-fill goose down and water-resistant Q.Shield technology.',
      price: 325,
      quantity: 1,
    ),
    Product(
      id: '50',
      name: 'Arc\'teryx Cerium LT Hoody',
      category: 'Outdoor',
      image: 'assets/jackets/5.png',
      description: 'Lightweight down jacket with strategic placement of synthetic insulation for warmth and packability.',
      price: 379,
      quantity: 1,
    ),
  ];

  static List<Product> laptops = [
    Product(
      id: '51',
      name: 'Apple MacBook Air M1',
      category: 'Ultrabook',
      image: 'assets/laptops/1.png',
      description:
      'Apple Silicon M1 chip with 8-core CPU and 7-core GPU, 13.3-inch Retina display, 256GB SSD storage.',
      price: 999,
      quantity: 1,
    ),
    Product(
      id: '52',
      name: 'Dell XPS 13',
      category: 'Ultrabook',
      image: 'assets/laptops/2.png',
      description:
      'Intel Core i7-1185G7, 13.4-inch 4K UHD+ touchscreen, 16GB RAM, 512GB SSD, Intel Iris Xe Graphics.',
      price: 1599,
      quantity: 1,
    ),
    Product(
      id: '53',
      name: 'HP Spectre x360 14',
      category: 'Convertible',
      image: 'assets/laptops/3.png',
      description:
      'Intel Core i7-1165G7, 13.5-inch OLED touch display, 16GB RAM, 1TB SSD, Intel Iris Xe Graphics.',
      price: 1499,
      quantity: 1,
    ),
    Product(
      id: '54',
      name: 'Lenovo ThinkPad X1 Carbon Gen 9',
      category: 'Business',
      image: 'assets/laptops/4.png',
      description:
      'Intel Core i7-1165G7, 14-inch 4K UHD+ display, 16GB RAM, 1TB SSD, Intel Iris Xe Graphics.',
      price: 1899,
      quantity: 1,
    ),
    Product(
      id: '55',
      name: 'ASUS ROG Zephyrus G14',
      category: 'Gaming',
      image: 'assets/laptops/5.png',
      description:
      'AMD Ryzen 9 5900HS, 14-inch QHD 120Hz display, 16GB RAM, 1TB SSD, NVIDIA GeForce RTX 3060.',
      price: 1799,
      quantity: 1,
    ),
    Product(
      id: '56',
      name: 'Acer Swift 5',
      category: 'Ultrabook',
      image: 'assets/laptops/1.png',
      description:
      'Intel Core i7-1165G7, 14-inch Full HD touchscreen, 16GB RAM, 1TB NVMe SSD, Intel Iris Xe Graphics.',
      price: 1099,
      quantity: 1,
    ),
    Product(
      id: '57',
      name: 'Microsoft Surface Laptop 4',
      category: 'Ultrabook',
      image: 'assets/laptops/2.png',
      description:
      'Intel Core i7-1185G7, 15-inch PixelSense touchscreen, 16GB RAM, 512GB SSD, Intel Iris Xe Graphics.',
      price: 1699,
      quantity: 1,
    ),
    Product(
      id: '58',
      name: 'Razer Blade 15',
      category: 'Gaming',
      image: 'assets/laptops/3.png',
      description:
      'Intel Core i7-10750H, 15.6-inch Full HD 144Hz display, 16GB RAM, 512GB SSD, NVIDIA GeForce RTX 3070.',
      price: 1999,
      quantity: 1,
    ),
    Product(
      id: '59',
      name: 'Samsung Galaxy Book Pro 360',
      category: 'Convertible',
      image: 'assets/laptops/4.png',
      description:
      'Intel Core i7-1165G7, 15.6-inch Super AMOLED touchscreen, 16GB RAM, 1TB NVMe SSD, Intel Iris Xe Graphics.',
      price: 1499,
      quantity: 1,
    ),
    Product(
      id: '60',
      name: 'HP Envy 15',
      category: 'Ultrabook',
      image: 'assets/laptops/5.png',
      description:
      'Intel Core i7-1165G7, 15.6-inch 4K UHD touchscreen, 16GB RAM, 1TB SSD, NVIDIA GeForce GTX 1650 Ti.',
      price: 1599,
      quantity: 1,
    ),
    Product(
      id: '61',
      name: 'Alienware m15 R5',
      category: 'Gaming',
      image: 'assets/laptops/1.png',
      description:
      'AMD Ryzen 9 5900HX, 15.6-inch QHD 240Hz display, 32GB RAM, 2TB SSD, NVIDIA GeForce RTX 3070.',
      price: 2599,
      quantity: 1,
    ),
    Product(
      id: '62',
      name: 'Apple MacBook Pro 14-inch M1 Pro',
      category: 'Professional',
      image: 'assets/laptops/2.png',
      description:
      'Apple Silicon M1 Pro chip with 10-core CPU and 16-core GPU, 14.2-inch Liquid Retina XDR display, 1TB SSD storage.',
      price: 1999,
      quantity: 1,
    ),
    Product(
      id: '63',
      name: 'Dell Latitude 9520',
      category: 'Business',
      image: 'assets/laptops/3.png',
      description:
      'Intel Core i7-1185G7, 15-inch Full HD touchscreen, 32GB RAM, 1TB SSD, Intel Iris Xe Graphics.',
      price: 2399,
      quantity: 1,
    ),
    Product(
      id: '64',
      name: 'Lenovo Legion 5 Pro',
      category: 'Gaming',
      image: 'assets/laptops/4.png',
      description:
      'AMD Ryzen 7 5800H, 16-inch QHD 165Hz display, 32GB RAM, 1TB SSD, NVIDIA GeForce RTX 3070.',
      price: 1799,
      quantity: 1,
    ),
    Product(
      id: '65',
      name: 'ASUS ZenBook Duo 14',
      category: 'Dual Screen',
      image: 'assets/laptops/5.png',
      description:
      'Intel Core i7-1165G7, 14-inch Full HD touchscreen and secondary 12.6-inch ScreenPad Plus display, 16GB RAM, 1TB SSD, Intel Iris Xe Graphics.',
      price: 1699,
      quantity: 1,
    ),
    Product(
      id: '66',
      name: 'Acer Predator Helios 300',
      category: 'Gaming',
      image: 'assets/laptops/1.png',
      description:
      'Intel Core i7-11800H, 15.6-inch Full HD 144Hz display, 16GB RAM, 512GB NVMe SSD, NVIDIA GeForce RTX 3060.',
      price: 1399,
      quantity: 1,
    ),
    Product(
      id: '67',
      name: 'Microsoft Surface Laptop Studio',
      category: 'Convertible',
      image: 'assets/laptops/2.png',
      description:
      'Intel Core i7-11370H, 14.4-inch PixelSense touchscreen with Surface Pen support, 32GB RAM, 1TB SSD, NVIDIA GeForce RTX 3050 Ti.',
      price: 2499,
      quantity: 1,
    ),
    Product(
      id: '68',
      name: 'Razer Blade Stealth 13',
      category: 'Ultrabook',
      image: 'assets/laptops/3.png',
      description:
      'Intel Core i7-1165G7, 13.3-inch Full HD touchscreen, 16GB RAM, 512GB SSD, NVIDIA GeForce GTX 1650 Ti Max-Q.',
      price: 1499,
      quantity: 1,
    ),
    Product(
      id: '69',
      name: 'Samsung Galaxy Book Flex 2',
      category: 'Convertible',
      image: 'assets/laptops/4.png',
      description:
      'Intel Core i7-1165G7, 15.6-inch QLED touchscreen with S Pen support, 16GB RAM, 1TB NVMe SSD, Intel Iris Xe Graphics.',
      price: 1399,
      quantity: 1,
    ),
    Product(
      id: '70',
      name: 'HP Omen 15',
      category: 'Gaming',
      image: 'assets/laptops/5.png',
      description:
      'Intel Core i7-11800H, 15.6-inch Full HD 144Hz display, 16GB RAM, 1TB SSD, NVIDIA GeForce RTX 3070.',
      price: 1799,
      quantity: 1,
    ),
    Product(
      id: '71',
      name: 'Acer Chromebook Spin 713',
      category: 'Chromebook',
      image: 'assets/laptops/1.png',
      description:
      'Intel Core i5-1135G7, 13.5-inch 2K VertiView touchscreen, 8GB RAM, 256GB NVMe SSD, Intel Iris Xe Graphics.',
      price: 629,
      quantity: 1,
    ),
    Product(
      id: '72',
      name: 'Lenovo Yoga 9i',
      category: 'Convertible',
      image: 'assets/laptops/2.png',
      description:
      'Intel Core i7-1185G7, 14-inch 4K UHD touchscreen with Dolby Vision HDR, 16GB RAM, 1TB SSD, Intel Iris Xe Graphics.',
      price: 1599,
      quantity: 1,
    ),
    Product(
      id: '73',
      name: 'ASUS ROG Strix G15',
      category: 'Gaming',
      image: 'assets/laptops/3.png',
      description:
      'AMD Ryzen 9 5900HX, 15.6-inch Full HD 300Hz display, 32GB RAM, 1TB SSD, NVIDIA GeForce RTX 3080.',
      price: 2299,
      quantity: 1,
    ),
    Product(
      id: '74',
      name: 'Dell Inspiron 14 5000',
      category: 'Ultrabook',
      image: 'assets/laptops/4.png',
      description:
      'Intel Core i7-1165G7, 14-inch Full HD touchscreen, 16GB RAM, 512GB SSD, Intel Iris Xe Graphics.',
      price: 999,
      quantity: 1,
    ),
    Product(
      id: '75',
      name: 'Microsoft Surface Pro 8',
      category: 'Tablet PC',
      image: 'assets/laptops/5.png',
      description:
      'Intel Core i7-1185G7, 13-inch PixelSense touchscreen, 16GB RAM, 512GB SSD, Intel Iris Xe Graphics.',
      price: 1299,
      quantity: 1,
    ),
  ];

  static List<Product> phones = [
    Product(
      id: '76',
      name: 'Apple iPhone 13 Pro',
      category: 'Smartphone',
      image: 'assets/phones/1.png',
      description:
      'Super Retina XDR display, A15 Bionic chip, Pro camera system with 12MP Ultra Wide, Wide, and Telephoto cameras, ProRAW, Night mode, 5G capable.',
      price: 999,
      quantity: 1,
    ),
    Product(
      id: '77',
      name: 'Samsung Galaxy S22 Ultra',
      category: 'Smartphone',
      image: 'assets/phones/2.png',
      description:
      '6.8-inch Dynamic AMOLED 2X display, Snapdragon 8 Gen 1 or Exynos 2200 chip, quad camera setup with 108MP main sensor, 5000mAh battery, S Pen support.',
      price: 1199,
      quantity: 1,
    ),
    Product(
      id: '78',
      name: 'Google Pixel 6 Pro',
      category: 'Smartphone',
      image: 'assets/phones/3.png',
      description:
      '6.7-inch Fluid AMOLED display, Google Tensor chip, 50MP main sensor, 12MP ultra-wide, 48MP telephoto, 5000mAh battery, 5G capable.',
      price: 899,
      quantity: 1,
    ),
    Product(
      id: '79',
      name: 'OnePlus 10 Pro',
      category: 'Smartphone',
      image: 'assets/phones/4.png',
      description:
      '6.7-inch Fluid AMOLED display, Snapdragon 8 Gen 1 chip, triple camera system with 50MP main sensor, 5000mAh battery, Warp Charge 65T.',
      price: 899,
      quantity: 1,
    ),
    Product(
      id: '80',
      name: 'Apple iPhone SE (2022)',
      category: 'Smartphone',
      image: 'assets/phones/5.png',
      description:
      '4.7-inch Retina HD display, A15 Bionic chip, single 12MP Wide camera, Touch ID, 5G capable, compact design.',
      price: 429,
      quantity: 1,
    ),
    Product(
      id: '81',
      name: 'Xiaomi Mi 12 Ultra',
      category: 'Smartphone',
      image: 'assets/phones/1.png',
      description:
      '6.8-inch AMOLED display, Snapdragon 8 Gen 1 chip, quad camera setup with 200MP main sensor, 5000mAh battery, 120W fast charging.',
      price: 1099,
      quantity: 1,
    ),
    Product(
      id: '82',
      name: 'Sony Xperia 1 III',
      category: 'Smartphone',
      image: 'assets/phones/2.png',
      description:
      '6.5-inch 4K OLED display, Snapdragon 888 chip, triple camera system with 12MP main sensor, 4500mAh battery, 5G capable, 120Hz refresh rate.',
      price: 1299,
      quantity: 1,
    ),
    Product(
      id: '83',
      name: 'Samsung Galaxy Z Fold 3',
      category: 'Foldable',
      image: 'assets/phones/3.png',
      description:
      '7.6-inch Dynamic AMOLED 2X main display, Snapdragon 888 chip, triple camera system, 4400mAh battery, S Pen support, water resistant.',
      price: 1799,
      quantity: 1,
    ),
    Product(
      id: '84',
      name: 'Xiaomi Redmi Note 11 Pro+',
      category: 'Smartphone',
      image: 'assets/phones/4.png',
      description:
      '6.67-inch AMOLED display, Snapdragon 695 chip, quad camera setup with 108MP main sensor, 5000mAh battery, 67W fast charging.',
      price: 499,
      quantity: 1,
    ),
    Product(
      id: '85',
      name: 'Google Pixel 5a 5G',
      category: 'Smartphone',
      image: 'assets/phones/5.png',
      description:
      '6.34-inch OLED display, Snapdragon 765G chip, dual camera system with 12.2MP main sensor, 4680mAh battery, 5G capable.',
      price: 449,
      quantity: 1,
    ),
    Product(
      id: '86',
      name: 'Motorola Edge 30 Ultra',
      category: 'Smartphone',
      image: 'assets/phones/1.png',
      description:
      '6.7-inch OLED display, Snapdragon 8 Gen 1 chip, triple camera system with 50MP main sensor, 5000mAh battery, 60W fast charging.',
      price: 899,
      quantity: 1,
    ),
    Product(
      id: '87',
      name: 'Apple iPhone 13 mini',
      category: 'Smartphone',
      image: 'assets/phones/2.png',
      description:
      'Super Retina XDR display, A15 Bionic chip, dual camera system with 12MP Wide and Ultra Wide cameras, 5G capable, compact design.',
      price: 699,
      quantity: 1,
    ),
    Product(
      id: '88',
      name: 'OnePlus 9 Pro',
      category: 'Smartphone',
      image: 'assets/phones/3.png',
      description:
      '6.7-inch Fluid AMOLED display, Snapdragon 888 chip, quad camera system with 48MP main sensor, 4500mAh battery, Warp Charge 65T.',
      price: 969,
      quantity: 1,
    ),
    Product(
      id: '89',
      name: 'Samsung Galaxy A53 5G',
      category: 'Smartphone',
      image: 'assets/phones/4.png',
      description:
      '6.5-inch Super AMOLED display, Snapdragon 778G chip, quad camera setup with 64MP main sensor, 4500mAh battery, 25W fast charging.',
      price: 449,
      quantity: 1,
    ),
    Product(
      id: '90',
      name: 'Xiaomi Poco X4 Pro 5G',
      category: 'Smartphone',
      image: 'assets/phones/5.png',
      description:
      '6.67-inch AMOLED display, Snapdragon 695 chip, quad camera setup with 108MP main sensor, 5000mAh battery, 67W fast charging.',
      price: 399,
      quantity: 1,
    ),
    Product(
      id: '91',
      name: 'Sony Xperia 5 III',
      category: 'Smartphone',
      image: 'assets/phones/1.png',
      description:
      '6.1-inch OLED display, Snapdragon 888 chip, triple camera system with 12MP main sensor, 4500mAh battery, 5G capable, 120Hz refresh rate.',
      price: 1099,
      quantity: 1,
    ),
    Product(
      id: '92',
      name: 'Realme GT 2 Pro',
      category: 'Smartphone',
      image: 'assets/phones/2.png',
      description:
      '6.7-inch Super AMOLED display, Snapdragon 8 Gen 1 chip, triple camera system with 50MP main sensor, 5000mAh battery, 65W fast charging.',
      price: 899,
      quantity: 1,
    ),
    Product(
      id: '93',
      name: 'Nokia X100',
      category: 'Smartphone',
      image: 'assets/phones/3.png',
      description:
      '6.67-inch IPS LCD display, Snapdragon 480 chip, quad camera setup with 48MP main sensor, 4470mAh battery, 18W fast charging.',
      price: 249,
      quantity: 1,
    ),
    Product(
      id: '94',
      name: 'LG Velvet 2 Pro 5G',
      category: 'Smartphone',
      image: 'assets/phones/4.png',
      description:
      '6.8-inch POLED display, Snapdragon 888 chip, triple camera system with 64MP main sensor, 4500mAh battery, 25W fast charging.',
      price: 599,
      quantity: 1,
    ),
    Product(
      id: '95',
      name: 'Motorola Moto G Stylus (2022)',
      category: 'Smartphone',
      image: 'assets/phones/5.png',
      description:
      '6.8-inch IPS LCD display, Snapdragon 678 chip, quad camera setup with 50MP main sensor, 5000mAh battery, 30W fast charging, built-in stylus.',
      price: 299,
      quantity: 1,
    ),
    Product(
      id: '96',
      name: 'Google Pixel 4a 5G',
      category: 'Smartphone',
      image: 'assets/phones/1.png',
      description:
      '6.2-inch OLED display, Snapdragon 765G chip, dual camera system with 12.2MP main sensor, 3885mAh battery, 5G capable.',
      price: 499,
      quantity: 1,
    ),
    Product(
      id: '97',
      name: 'Samsung Galaxy M52 5G',
      category: 'Smartphone',
      image: 'assets/phones/2.png',
      description:
      '6.7-inch Super AMOLED Plus display, Snapdragon 778G chip, triple camera setup with 64MP main sensor, 5000mAh battery, 25W fast charging.',
      price: 379,
      quantity: 1,
    ),
    Product(
      id: '98',
      name: 'Xiaomi Redmi Note 10 Pro',
      category: 'Smartphone',
      image: 'assets/phones/3.png',
      description:
      '6.67-inch Super AMOLED display, Snapdragon 732G chip, quad camera setup with 108MP main sensor, 5020mAh battery, 33W fast charging.',
      price: 279,
      quantity: 1,
    ),
    Product(
      id: '99',
      name: 'OnePlus Nord 2',
      category: 'Smartphone',
      image: 'assets/phones/4.png',
      description:
      '6.43-inch Fluid AMOLED display, MediaTek Dimensity 1200 AI chip, triple camera system with 50MP main sensor, 4500mAh battery, Warp Charge 65T.',
      price: 399,
      quantity: 1,
    ),
    Product(
      id: '100',
      name: 'Apple iPhone SE (2020)',
      category: 'Smartphone',
      image: 'assets/phones/5.png',
      description:
      '4.7-inch Retina HD display, A13 Bionic chip, single 12MP Wide camera, Touch ID, compact design.',
      price: 399,
      quantity: 1,
    ),
  ];

  static List<Product> tShirts = [
    Product(
      id: '101',
      name: 'Adidas Originals Trefoil Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/1.png',
      description:
      'Classic Adidas Originals Trefoil logo tee, made from 100% cotton for comfort and breathability.',
      price: 25,
      quantity: 1,
    ),
    Product(
      id: '102',
      name: 'Nike Sportswear Club Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/2.png',
      description:
      'Nike Sportswear Club tee with embroidered Nike logo, crafted from soft cotton jersey fabric.',
      price: 20,
      quantity: 1,
    ),
    Product(
      id: '103',
      name: 'Under Armour Men\'s Tech 2.0 Short Sleeve Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/3.png',
      description:
      'Under Armour Tech 2.0 tee featuring quick-drying, ultra-soft fabric for superior comfort during workouts.',
      price: 30,
      quantity: 1,
    ),
    Product(
      id: '104',
      name: 'Puma Essentials Logo Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/4.png',
      description:
      'Puma Essentials logo tee made from 100% cotton, featuring a classic crew neck design and Puma logo.',
      price: 22,
      quantity: 1,
    ),
    Product(
      id: '105',
      name: 'Levi\'s Men\'s Graphic Set-In Neck Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/5.png',
      description:
      'Levi\'s graphic tee with iconic Levi\'s logo print, made from soft and comfortable cotton jersey fabric.',
      price: 28,
      quantity: 1,
    ),
    Product(
      id: '106',
      name: 'Hanes Men\'s ComfortSoft Short Sleeve T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/1.png',
      description:
      'Hanes ComfortSoft tee with Tagless label for itch-free comfort, made from 100% preshrunk ComfortSoft cotton.',
      price: 15,
      quantity: 1,
    ),
    Product(
      id: '107',
      name: 'Fruit of the Loom Men\'s Crew T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/2.png',
      description:
      'Fruit of the Loom crew neck tee, made from 100% cotton for softness and durability, suitable for everyday wear.',
      price: 18,
      quantity: 1,
    ),
    Product(
      id: '108',
      name: 'Champion Classic Jersey Script Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/3.png',
      description:
      'Champion Classic Jersey tee featuring Champion script logo on the chest, made from ring-spun cotton for a softer feel.',
      price: 24,
      quantity: 1,
    ),
    Product(
      id: '109',
      name: 'Tommy Hilfiger Men\'s Flag Crew Neck Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/4.png',
      description:
      'Tommy Hilfiger crew neck tee with embroidered flag logo on chest, made from premium cotton jersey fabric.',
      price: 32,
      quantity: 1,
    ),
    Product(
      id: '110',
      name: 'Gap Essential Crewneck T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/5.png',
      description:
      'Gap Essential tee crafted from soft, premium jersey cotton for a comfortable fit and feel.',
      price: 19,
      quantity: 1,
    ),
    Product(
      id: '111',
      name: 'American Eagle Men\'s Heritage Pocket T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/1.png',
      description:
      'American Eagle Heritage tee with pocket, made from soft cotton jersey and garment-dyed for a vintage look.',
      price: 26,
      quantity: 1,
    ),
    Product(
      id: '112',
      name: 'Abercrombie & Fitch Men\'s Short Sleeve Logo Tee',
      category: 'T-Shirt',
      image: 'assets/tshirts/2.png',
      description:
      'Abercrombie & Fitch logo tee featuring printed logo graphic on soft cotton jersey fabric.',
      price: 29,
      quantity: 1,
    ),
    Product(
      id: '113',
      name: 'Ralph Lauren Men\'s Classic Fit Crewneck T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/3.png',
      description:
      'Ralph Lauren Classic Fit tee with signature embroidered pony logo, made from premium cotton jersey.',
      price: 35,
      quantity: 1,
    ),
    Product(
      id: '114',
      name: 'Vans Classic T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/4.png',
      description:
      'Vans Classic tee with Vans logo print, made from 100% ringspun cotton for a soft feel and durability.',
      price: 25,
      quantity: 1,
    ),
    Product(
      id: '115',
      name: 'Calvin Klein Men\'s Short Sleeve Logo T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/5.png',
      description:
      'Calvin Klein logo tee featuring printed CK logo on chest, made from soft and comfortable cotton jersey fabric.',
      price: 27,
      quantity: 1,
    ),
    Product(
      id: '116',
      name: 'Lacoste Men\'s Cotton Jersey T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/1.png',
      description:
      'Lacoste crew neck tee made from luxurious Pima cotton jersey, featuring iconic Lacoste crocodile logo.',
      price: 39,
      quantity: 1,
    ),
    Product(
      id: '117',
      name: 'Aéropostale Solid Crew Neck T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/2.png',
      description:
      'Aéropostale solid crew neck tee, made from soft and breathable cotton for everyday comfort.',
      price: 20,
      quantity: 1,
    ),
    Product(
      id: '118',
      name: 'Guess Men\'s Short Sleeve Triangle Logo T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/3.png',
      description:
      'Guess Triangle Logo tee featuring printed logo graphic on chest, made from comfortable cotton jersey.',
      price: 30,
      quantity: 1,
    ),
    Product(
      id: '119',
      name: 'Hollister Men\'s Must-Have Crew T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/4.png',
      description:
      'Hollister Must-Have tee with logo graphic, crafted from soft cotton jersey for all-day comfort.',
      price: 22,
      quantity: 1,
    ),
    Product(
      id: '120',
      name: 'Superdry Men\'s Vintage Logo Tri T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/5.png',
      description:
      'Superdry Vintage Logo Tri tee featuring textured logo print on chest, made from soft cotton fabric.',
      price: 32,
      quantity: 1,
    ),
    Product(
      id: '121',
      name: 'Diesel Men\'s T-Diego-Division Logo T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/1.png',
      description:
      'Diesel T-Diego-Division Logo tee with logo graphic, made from soft cotton jersey for a comfortable fit.',
      price: 35,
      quantity: 1,
    ),
    Product(
      id: '122',
      name: 'Gap Essential V-Neck T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/2.png',
      description:
      'Gap Essential V-Neck tee crafted from soft, premium jersey cotton for a comfortable and relaxed fit.',
      price: 18,
      quantity: 1,
    ),
    Product(
      id: '123',
      name: 'Tommy Jeans Men\'s T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/3.png',
      description:
      'Tommy Jeans Essential Flag tee with Tommy Jeans logo and flag embroidery, made from soft cotton jersey.',
      price: 29,
      quantity: 1,
    ),
    Product(
      id: '124',
      name: 'American Eagle Men\'s AE Surf Co. Graphic T-Shirt',
      category: 'T-Shirt',
      image: 'assets/tshirts/4.png',
      description:
      'American Eagle AE Surf Co. Graphic tee with printed graphic on chest, made from soft cotton jersey.',
      price: 25,
      quantity: 1,
    ),
    Product(
      id: '125',
      name: 'Abercrombie & Fitch Men\'s Short Sleeve Henley',
      category: 'T-Shirt',
      image: 'assets/tshirts/5.png',
      description:
      'Abercrombie & Fitch Henley tee with button placket and logo embroidery, made from soft slub cotton.',
      price: 34,
      quantity: 1,
    ),
  ];





}